### ISSUE TITLE
Bibletime doesn't start (have win 7)

### ISSUE THREAD

**Issue by kauraves** [bibletime/bibletime#113]
I installed the latest Bibletime version from Github as Administrator. After installation when I try to start the programme I get in the Windows log the following error message in Finnish. It complains about module ucrtbase.DLL. I have Visual Studio 2017 installed. I don't know if it has some effects.

Viallisen sovelluksen nimi: bibletime.exe, versio: 0.0.0.0, aikaleima: 0x585b6712
Viallisen moduulin nimi: ucrtbase.DLL, versio: 10.0.10586.788, aikaleima: 0x5879aa7b
Poikkeuskoodi: 0x40000015
Virhepoikkeama: 0x0008469a
Viallisen prosessin tunnus: 0x1cfc
Viallisen sovelluksen käynnistysaika: 0x01d30fb11129a9b1
Viallisen sovelluksen polku: C:\Program Files (x86)\BibleTime\bin\bibletime.exe
Viallisen moduulin polku: C:\Windows\system32\ucrtbase.DLL
Raportin tunnus: 4f18a563-7ba4-11e7-99ce-48d224093977

**Comment by gholmlund** [comment]
It is hard to tell the issue from this report, but I suspect it is the same as bug #90. This has been fixed but we need to have a new release (2.11.1)

**Comment by jaakristioja** [comment]
@kauraves Can you please try with version 2.11.1 and tell us whether the issue persists?

**Comment by gholmlund** [comment]
After seeing you are using version 2.11.0, I thought about older bug already fixed and realized that this is a duplicate of bug #90. I am confident that version 2.11.1 will fix this issue.
