### ISSUE TITLE
Can't access Judith or Wisdom

### ISSUE THREAD

**Issue by Merlignux** [bibletime/bibletime#130]
In the pt-pt translation (with Capuchinhos version - PorCap) i can't access the books of Wisdom (Sabedoria) or Judith (Judite).

I go to the books selector and if i select Judith or Wisdom it always opens Revelation (Apocalipse).

I think it's probably somekind of "linkage" problem.

This happens in both Desktop and Mobile versions

**Comment by gholmlund** [comment]
I was able to duplicate this on Mobile. I would like to duplicate it on the Desktop, but have not been able to. Please tell me which version of BibleTime and Sword you are using. Check from the menu Help/About.

**Comment by Merlignux** [comment]
Hi Gary.

On the Desktop I'm using BibleTime 2.11.1 with SWORD 1.7.5

**Comment by greg-hellings** [comment]
That's interesting, because SWORD 1.7.5 doesn't exist.

**Comment by Merlignux** [comment]
Now, that's weird!!!

![weird](https://user-images.githubusercontent.com/8130393/34921882-de0e4160-f97f-11e7-88f5-b614cee79dd8.jpg)

**Comment by greg-hellings** [comment]
Try building against a released version of SWORD. There was a 1.7.5 alpha
but  there were problems that prevented its release

**Comment by Merlignux** [comment]
Manually building it is a bit too technical for me. Anyway, i downloaded the last version of BibleTime and reinstalled it, but it kept showing 1.7.5 as Sword version...

**Comment by gholmlund** [comment]
I released BibleTime for Windows with 1.7.5a because it fixed several problems with 1.7.4. These problems were related to access to the extra books in Portuguese. Merlignux, I believe you originally reported these problems to me. I assume you are seeing this problem on Windows (and mobile). I was able to see this problem on mobile and have debugged it enough to know that the problem is in Sword. Debugging on mobile (Android) is very slow because the debugger and application are running on a remote computer  (Android device) and not on my linux development computer. I have tried to reproduce this problem on BibleTime for Windows, but I don't see it there. I also don't see it on linux. I have tried it with BibleTime 2.11.1 with both 1.7.4 and 1.8.1 sword. 
I will keep working on this, but it make take a little time to understand and get fixed.

**Comment by gholmlund** [comment]
I understand it better now. Previously I had forgot to switch the Bible book names to Portuguese. I can reproduce the problem with all versions of Sword.

Description:
Open the PorCap Bible. Using English book names go to Judith or Wisdom. They display correctly. Then switch to Portuguese book names. Switch to another book and then try to switch to Judite or Sabedoria. It will not switch. This is with Sword 1.8.1.  The symptoms are slightly different in 1.7.4.

**Comment by gholmlund** [comment]
After debugging through Sword, I found the problem. The locales.d/pt-utf8.conf file has incorrect abbreviations for Judith and Wisdom. The correct abbreviations as seen in canon_catholic.h are "Jdt" and "Wis". 
 diff pt-utf8.conf.orig  pt-utf8.conf
117,118c117,118
< JUDITE=Jth
< JDT=Jth
---
> JUDITE=Jdt
> JDT=Jdt
134,135c134,135
< SABEDORIA=Ws
< SB=Ws
---
> SABEDORIA=Wis
> SB=Wis

Merlignux, you should be able to edit this file and fix your problem. I will submit a defect to Sword about this.

**Comment by gholmlund** [comment]
Submitted to Sword
SWORD API-206

**Comment by Merlignux** [comment]
@gholmlund Yes, It was i that reported this to you (by e-mail, i think).
At the time, if my memory isn't playing tricks on me, i translated the booknames, but i don't remember if i've done anything to the abbreviations...

I probably missed them or didn't touch them at all...

could you provide the link to the submitted bug at sword?

**Comment by Merlignux** [comment]
I agree, If they would release a v1.8.2 that would be great!!!

**Comment by gholmlund** [comment]
I have released a new version of BibleTime for Windows. It has Sword 1.8.1 and Qt 5.10.0. It also has the modified pt-utf8.conf.

**Comment by Merlignux** [comment]
@gholmlund it's still not available for download. Is that normal? or am i looking in the wrong place?

**Comment by gholmlund** [comment]
It is on the github releases page. It has anextra "-2" in the name.
https://github.com/bibletime/bibletime/releases

**Comment by Merlignux** [comment]
Ups... i missed that one!!! Thanks. (downloading...)

Any ETA for BTM?

**Comment by gholmlund** [comment]
BTM may be a few days away. I am seeing a problem with Sword 1.8.1 and I don't understand it yet.

**Comment by gholmlund** [comment]
BTM (Mobile) is released.

**Comment by Merlignux** [comment]
Thank you once again Gary!!!
