### ISSUE TITLE
error when clicking on book/ch/verse in results of a search

### ISSUE THREAD

**Issue by timsoftgit** [bibletime/bibletime#233]
with rc1 I get 2 errors/warnings. (1 error/warning with beta2 ) 
To replicate:. run bibletime with KJV and strongs hebrew and strongs greek installed with sword library 1.8.1 (with the pkg-config patch)
start xwindows as regular user, open Konsole
run bibletime
as expected bibletime starts up and shows the last location it was opened at (defaults to rev1v1 on clean install). you can browse as expected and mag works. Click on binoculars (search) and search for 

> praise

 and click Search
in rc_1 i get on the Konsole 
`(BibleTime 3.0.0_rc1) WARNING: QCssParser::parseHexColor: Unknown color name '#FOREGROUND_COLOR'`
the results of the search are shown under results (first match Genesis 29:35 ) and in the preview it shows the verse of the first match with a verse either side. (beta2 highlights the found word in yellow, but rc1 does not)
If you click on the verse link in the preview, bibletime blanks the preview, and on the Konsole gives the message
`(BibleTime 3.0.0_rc1) WARNING: QTextBrowser: No document for sword://bibile/KJV/Genesis 29:35`
I get a similar warning message for bibletime 3.0.0_beta2
I am running with qt5.12.8 and all the libs are available, although cmake is an older version (3.5.2) so I had to do some patches to BTApplication.cmake in order for it to compile.
any ideas on how to squash the first warning, and fix the behaviour of the second?
my os is slackware14.2 and I'm trying to prepare the build package for the new release.

**Comment by jaakristioja** [comment]
> as expected bibletime starts up and shows the last location it was opened at (defaults to rev1v1 on clean install). you can browse as expected and mag works. Click on binoculars (search) and search for
> 
> > praise
> 
> and click Search
> in rc_1 i get on the Konsole
> `(BibleTime 3.0.0_rc1) WARNING: QCssParser::parseHexColor: Unknown color name '#FOREGROUND_COLOR'`
> the results of the search are shown under results (first match Genesis 29:35 ) and in the preview it shows the verse of the first match with a verse either side. (beta2 highlights the found word in yellow, but rc1 does not)

@gholmlund This looks like a regression from 3.0_beta2 to 3.0_rc1. Perhaps related to a8ee059d67c78064a06926fbf5c1c6bd91a54783 ?

**Comment by gholmlund** [comment]
Fixed.

**Comment by gholmlund** [comment]
Search highlighting working now

**Comment by timsoftgit** [comment]
That patch has fixed the highlighting and #FOREGROUND_COLOR error. many thanks. The

> WARNING: QTextBrowser: No document for sword://bible/KJV/Genesis 29:35

error, and blanking of search reselts when clicking on the ch/verse link in the results preview still occurs.

**Comment by jaakristioja** [comment]
@gholmlund Thank you for fixing the highlighting.
@timsoftgit Please try to file separate GitHub issues next time. It makes tracking separate problems easier for us.

**Comment by gholmlund** [comment]
Fixed the problem with clicking a verse. It does nothing which is consistent with previous versions.

**Comment by timsoftgit** [comment]
will do, sorry about that. 
I can confirm that your latest update stops the search preview blanking and removes the terminal warning message as well, thanks very much. if you are interested I can post the patches to make bibletime work with cmake 3.5.2 somewhere. When we get to the next tagged or release version of bibletime I'll be able to upload the slackbuild to slackbuilds.org

**Comment by jaakristioja** [comment]
@timsoftgit We will not start to support earlier versions of CMake again. Instead we might decide to migrate to some newer version of CMake.

If someone wants to build BibleTime using some earlier version of CMake, then they must do their own patching. For slackbuilds, you might be interested in [this guide](https://www.slackwiki.com/Writing_A_SlackBuild_Script#Patching_the_Sources).

Backwards compatibility with older versions of CMake is not a big concern for us, because one can easily compile / download a newer version of CMake to use. In fact, I've done setups where the build system automatically compiles and switches to a newer version of CMake if it detects that the version of CMake used to invoke it is too old. Trying to be backwards compatible with older versions of CMake in other ways that this would only further slow down development for us.

**Comment by timsoftgit** [comment]
No problem, I didn't really expect you to go back to a version of cmake that old. It is only useful for older systems that want the latest bibletime.
