### ISSUE TITLE
The preview on Settings dialog displays text as red.

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#299]
> The preview on Settings dialog displays text as red. And BT shows black text when i have set it so. I mean that preview is not wysiwyg. Text colors are different.

_Originally posted by @ilkant in https://github.com/bibletime/bibletime/issues/298#issuecomment-781028766_

**Comment by jaakristioja** [comment]
I can also confirm this.

**Comment by gholmlund** [comment]
Fixed in master and stable-3.0 branches

**Comment by jaakristioja** [comment]
@gholmlund I'm not sure this fixed it, I'm still seeing the text as red or red-ish in the settings dialog, except I select HighContrast.css as the display style.

**Comment by gholmlund** [comment]
All styles except HighContrast should be red. HighContrast has no specified color for Jesus words.
The original defect was about adding a new style that did not use red for Jesus words.

**Comment by jaakristioja** [comment]
Ah, you're absolutely correct! Thanks! Closing.

PS: I opened a new issue for about the sample text: #306
