### ISSUE TITLE
[BUG] Scrolling the QML view with Page Up and Page Down keys past content yields strange results

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#331]
**Describe the bug**

Using <kbd>PageUp</kbd>/<kbd>PageDown</kbd> keys one can scroll past the content of the QML view and this causes weird results, including rendering errors and jumping to arbitrary references (e.g. from Genesis 1:1 to Revelation of John 1:1).

**To Reproduce**
1. Open a Bible and navigate to Genesis 1:1 (or the last verse of the Book of Revelation)
2. Press <kbd>PageUp</kbd> to scroll up from Genesis 1:1 (or <kbd>PageDown</kbd> to scroll past the end of the Bible)
3. Optionally repeat step 2

**Expected behavior**
The view should not scroll past the contents, and everything should render properly, it should not jump to arbitrary references.

**System information (please complete the following information):**
 - OS and OS version: Gentoo Linux
 - Both BibleTime 3.0 & git master
 - Qt 5.15.2

This behavior is really strange, and I think it would be reasonable to fix this for 3.0.1 even if it delays the release a bit.

**Comment by gholmlund** [comment]
Fixed. 
This behavior is due to Qt, but I found a way to work around it.

**Comment by jaakristioja** [comment]
This almost fixed it, but I'm still seeing one type of weird behavior. For example, with only AKJV open:

* when I <kbd>PageUp</kbd> all the way to the beginning of the module and then press <kbd>PageUp</kbd> again, all contents after verse 1:9 (Genesis) disappear.
* when I <kbd>PageDown</kbd> all the way to the end of the module and then press <kbd>PageDown</kbd> again, all contents before verse 22:8 (Revelation of John) disappear.

Pressing <kbd>PageUp</kbd>/<kbd>PageDown</kbd> again and again just seems to continue to toggle the visibility of the contents. I don't think this is just a rendering error. It seems that the disappeared contents are just not there, because hovering over them does not cause the mouse cursor to change as it changes when the items are visible.

**Comment by gholmlund** [comment]
@jaakristioja  The page up/down is pushing the beyond the lower or upper bounds of the model. I believe the ListView cache is behaving wrong in this case. A small number of items are created by the cache and reused as they scroll out of the view. In this case it appears to be clearing the item properties, but not reloading the properties (text). So, it is displaying empty text. 

I have been searching Qt docs and code and have found a way to fix this. It is a property of Flickable that won't let the ListView items to move beyond a valid range. It is Flickable.boundsMovement.StopAtBounds. Unfortunately, this property is new in Qt 5.10. We are currently requiring Qt 5.9 in the stable branch. I don't believe we will find another fix.

**Comment by jaakristioja** [comment]
If that works, please apply the fix to master if possible. For the stable branch, I think it will suffice to make it conditional, e.g. using `#if QT_VERSION >= QT_VERSION_CHECK(5, 9, 0)` or some QML equivalent of that (using a run-time check would also okay).

The cache issue is not as severe as what you already fixed using `returnToBounds()`, so only users on platforms with Qt 5.9 would have to continue to endure it. Stable versions of Debian and Ubuntu (and the myriad of their derivatives) have newer versions of Qt, so this would fix it for the majority of our users.

**Comment by gholmlund** [comment]
Fixed and tested with Qt 5.9.9 and 5.15.2. It works as expected.
I also had to fix a couple of other problems with using Qt 5.9.x

**Comment by jaakristioja** [comment]
I can confirm it works properly for me now. Thanks, @gholmlund !
