### ISSUE TITLE
Booknames Untranslated

### ISSUE THREAD

**Issue by Merlignux** [bibletime/bibletime#61]
I believe this is a Sword problem, but some book names are not translated (e.g.: Tobit, Judith, I Maccabees, II Maccabees Wisdom, etc...)

**Comment by mgruner** [comment]
Yep, this is not handled by BibleTime.

**Comment by Merlignux** [comment]
Hi @mgruner 

I requested correction for this with sword, however they told me that from their side it's all already translated (the books have the correct/translated names for a long time already).
<
They indicated that it must be a BibleTime problem, probably libsword last version is not being used.

Could you please reopen the bug and check what's wrong with it?

Thanks

**Comment by jaakristioja** [comment]
I didn't find any such strings in the BibleTime sources, so it clearly isn't a directly related to Bibletime. 

Assuming that you're building from source on Linux, what version of Sword does `cmake` report when you configure? In additional, try running `ldd' on the resulting `bibletime` executable to see which sword library it is linking against. Adjust the `LD_LIBRARY_PATH` environment variable to BibleTime accordingly if you wish at run time to link with a Sword library in some other location.

**Comment by Merlignux** [comment]
I'm attaching a screenshot and the translated file i sent Sword.
This happens not only on Linux, but also on Windows (the mobile version also had the same problem, but is now fixed)

I also wondered if the pt-pt is not getting the pt-br version. I say this because the translation for the book of Job, in pt-pt is actually "Job" and the Brazilian ( AFAIK ) is "Jó"...

@jaakristioja can't try it on Linux ATM...  Will be away from a Linux box for a few days.

![bibletime](https://cloud.githubusercontent.com/assets/8130393/23325208/842faeba-faeb-11e6-98f3-6a7d92c88eaa.jpg)

[pt-utf8.zip](https://github.com/bibletime/bibletime/files/800711/pt-utf8.zip)

**Comment by gholmlund** [comment]
These translations are handled in the sword project in the sword/locales.d/pt*.conf for Portuguese. Looking at sword version 1.7.4 for Tobit and Judith, I see translations for these in the pt*.conf files. Looking at sword version 1.7.5a1 and in the HEAD of svn these translations are not there.

BibleTime for Windows used 1.7.5a1 which is listed as the current sword version.
http://www.crosswire.org/sword/develop/index.jsp

**Comment by gholmlund** [comment]
CORRECTION: The sword-1.7.4 files I examined were a local version that I had edited to add these books. I must have investigated this before around May 2015. I believe I submitted a bug report to sword, but their bug server is currently down and I can't verify this.

So, the problem is in sword and there has never been a translation for Tobit and Judith. I checked their svn history.

**Comment by Merlignux** [comment]
hi @gholmlund 
Nice to have you in :). I recall you saying that you submitted the corrected/translated files (don't know if it were in the form of bug, however). But for sure they were sent. I also created a bug report, i think more than a year later ( http://www.crosswire.org/tracker/browse/MOD-316 ).

Since i got no response (the bug never got fixed) i contacted them by e-mail and that's were Peter told me the files i sent them (also attached above) were already applied (the files you sent them, probably) and that maybe it was a problem in BibleTime (libsword not up-to-date)... I think i'll better ask his help on clarifying this.

**Comment by Merlignux** [comment]
Ok, i got a reply from Peter. He says the correct names are in libsword svn-head, but that, however, the Brasilian translation does not contain the names.

That, plus the name for the book of Job (Brasilian = Jó; Portugal = Job) leads me to think that the Portuguese translation is getting the Brasilian booknames instead of the Portuguese ones. Its the only logical deduction from my point of view...

**Comment by gholmlund** [comment]
I just checked out sword svn-head. The Portugal file has "Jó" which is wrong.
pt_BR-utf8.conf:Job=Jó
pt-utf8.conf:Job=Jó

Also, neither file contains any of the Apocrypha books!

**Comment by Merlignux** [comment]
OK, mystery solved guys!!!

You are right, Peter apologizes!!! (and I apologize as well for bringing so much "noise" to this bug)

What happened was that Peter had some problems a few months ago with committing not being succeed  pushed in. He assumed that what he had was svn-head, when in reality it was svn-head + uncommitted
changes.

I checked and it's now (at least) in trunk ( [PT-UTF8.Conf](http://www.crosswire.org/svn/sword/trunk/locales.d/pt-utf8.conf) )

**Thank you all :)**

Hope this is enough to get it in a next update :)

**Comment by gholmlund** [comment]
Now in svn I see pt-utf8.conf is fixed, but pt_br.conf is not. It does not have the Apocrypha books.

**Comment by Merlignux** [comment]
@gholmlund I didn't fix the Brazilian file (pt_br) because i'm from Portugal and sometimes "pt != pt_br" in some cases there are really significant differences. But i'll investigate it in order to not make mistakes and i'll submit a fix as soon as i get a bit of free time :)

**Comment by Merlignux** [comment]
Brazilian version translated and sent to Sword. 

Copy attached ;)

[pt_BR-utf8.zip](https://github.com/bibletime/bibletime/files/817946/pt_BR-utf8.zip)
