### ISSUE TITLE
segfault w/ v2.11_rc1-69-g35950d2

### ISSUE THREAD

**Issue by Geremia** [bibletime/bibletime#75]
I see a couple issues:

1. It doesn't recognize a "BibleTime Bookmark XML file"
2. It says "Running without the SUID sandbox!"

I didn't get these issues with 2.10.1. (However, trying to build that version threw some compiler errors in `cswordmoduleinfo.cpp` around line 57.)

build: v2.11_rc1-69-g35950d2
```
(BibleTime 2.11.0_rc1+95a393cc93edb58113538bd9d56361134d5929ab) WARNING: Not a BibleTime Bookmark XML file
[0927/094635:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Received signal Received signal 44 ILL_ILLOPN  ILL_ILLOPN 7f41715e42507f41715e4250

##00  0x0x7f4171a2d5ae7f4171a2d5ae  <unknown>
#1 0x7f4171a2d969 <unknown>
#2 0x7f416d5245b0 <unknown>
#3 0x7f41715e4250 <unknown>
#4 0x7f417247f9b0 <unknown>
#1 0x7f4171a2d969 <unknown>
#2 0x7f416d5245b0 <unknown>
#3 0x7f41715e4250 <unknown>
<unknown>#
4# 50x 7f417247f9b00x 7f417247fd91 <unknown><unknown>

##65  0x0x7f417247e85c7f417247fd91  <unknown>
#6 0x7f417247e85c <unknown>
#7 0x7f417247ef4c <unknown>
#8 0x7f4172c0f11a <unknown>
#9 0x7f41711198a9 <unknown>
#10 0x7f41711199e2 <unknown>
#11 0x7f41710f140f<unknown> 
#7 0x7f417247ef4c <unknown>
#8 0x7f4172c0f11a <unknown>
#9 0x7f41711198a9 <unknown>
#10 0x7f41711199e2 <unknown>
#11 0x7f41710f140f <unknown>
#12 0x7f4172c25838 <unknown>
#13 <unknown>0x
7f41710be148# 12 0x7f4172c25838 <unknown>
#13 0x7f41710be148 <unknown>
#14 0x7f417178a202 <unknown>
#15 0x7f41717a408a <unknown>
#16 0x7f41717a8e91 <unknown>
#17 0x7f417179b218 <unknown>
#18<unknown> 
0x#7f4170a602a014  0x7f417178a202 <unknown>
#15 0x7f41717a408a <unknown>
#16 0x7f41717a8e91 <unknown>
#17 0x7f417179b218 <unknown>
#18 0x7f4170a602a0 <unknown>
#19 0x7f41716dd110 <unknown>
#20 0x<unknown>7f4171a9e569
 #19 0x7f41716dd110 <unknown>
#20 0x7f4171a9e569 <unknown>
#21 0x7f417218dcc7 <unknown>
#22 0x7f417218e4b9 <unknown>
#23 0x7f4171a9e569 <unknown>
#24 0x7f4171a49409 <unknown>
<unknown>#
25# 210x 7f4171a4a0090x 7f417218dcc7 <unknown><unknown>

##2226  0x0x7f417218e4b97f4171a4a4cd  <unknown>
#27 0x7f4171a4c339 <unknown>
#28 0x7f4171a5e218 <unknown>
#29 0x7f4171a48745 <unknown>
#30 0x7f41717be2c0 <unknown>
#31 0x7f4170c9492c <unknown>
#32 0x<unknown>7f4170c94e87
 #23 0x7f4171a9e569 <unknown>
#24 0x7f4171a49409 <unknown>
#25 0x7f4171a4a009 <unknown>
#26 0x7f4171a4a4cd <unknown>
#27 0x7f4171a4c339 <unknown>
#28 0x7f4171a5e218 <unknown>
#29 0x<unknown>7f4171a48745
 #33 0x7f4170c94471 <unknown>
#34 0x7f4170197609 <unknown>
#35 0x000000400833 <unknown>
#36 0x7f416c8d3350 <unknown>
#30 0x7f41717be2c0 __libc_start_main
<unknown>#
37# 310x 00000040087a0x 7f4170c9492c <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 00007f416cc73b68 r11: 0000000000000202
 r12: 0000000000f30490 r13: 0000000000020000 r14: 0000000000f2f740 r15: 000015313d020008
  di: 000004c7ee641000  si: 000000000001e000  bp: 0000000000ec93c0  bx: 0000000000f30498
  dx: 0000000000000008  ax: ffffffffffffffff  cx: ffffffffffffff60  sp: 00007ffca319ec40
  ip: 00007f41715e4250 efl: 0000000000010286 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000<unknown> cr2: 
0000000000000000#
32[end of stack trace]
 0x7f4170c94e87 <unknown>
#33 0x7f4170c94471 <unknown>
#34 0x7f4170197609 QtWebEngine::processMain()
#35 0x000000400833 <unknown>
#36 0x7f416c8d3350 __libc_start_main
#37 0x00000040087a <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 00007f416cc73b68 r11: 0000000000000202
 r12: 0000000000f30420 r13: 0000000000020000 r14: 0000000000f2f6d0 r15: 00001727eac20008
  di: 00001eef96d21000  si: 000000000001e000  bp: 0000000000ec9790  bx: 0000000000f30428
  dx: 0000000000000008  ax: ffffffffffffffff  cx: ffffffffffffff60  sp: 00007ffca319ec40
  ip: 00007f41715e4250 efl: 0000000000010286 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

**Comment by jaakristioja** [comment]
I suspect this is rather some Qt web component issue and we can't fix or reasonably work it in BibleTime.

**Comment by Geremia** [comment]
@jaakristioja What more info should I provide regarding this?

**Comment by gholmlund** [comment]
If this was done with Qt 5.7 please test again with the latest stable-2.11 code. I fixed a crash with Qt 5.7 after the rc2 release.

NOTE: The "Running without the SUID sandbox!" is a harmless Qt warning. The warning has in fact been removed from Qt 5.7.1.  See QTBUG-54225.

**Comment by jaakristioja** [comment]
@Geremia What OS are you running this on? Can you reproduce the backtrace with debug symbols installed and enabled for QtWeb* components? Can you then run BibleTime in `gdb` and when it crashes, paste the output of `thread apply all bt` and `thread apply all bt full` from the GDB console?

The signal SIG_ILL with ILL_ILLOPN (illegal operand) usually points to some JIT compilation error. So unless your C++ compiler generates invalid machine code for BibleTime, it is likely a Qt/Chromium error. BibleTime doesn't have anything this advanced which would generally lead to such errors, even in case of undefined behavior.

**Comment by Geremia** [comment]
@gholmlund I still get the crash with stable-2.11. Perhaps it is something with Qt.

@jaakristioja Linux (4.4.20 kernel).

Here're the `gdb` outputs you requested:
[gdb.txt](https://github.com/bibletime/bibletime/files/514203/gdb.txt)

It does appear to be a QtWebEngineCore bug:
```
Thread 1 "bibletime" received signal SIGSEGV, Segmentation fault.
0x00007ffff1cfa0da in QtWebEngineCore::UserResourceControllerHost::WebContentsObserverHelper::RenderViewHostChanged(content::RenderViewHost*, content::RenderViewHost*) ()
   from /usr/lib64/libQt5WebEngineCore.so.5
```

**Comment by gholmlund** [comment]
Jaak, this appears to be the same bug you reported to Qt in August.
https://bugreports.qt.io/browse/QTBUG-55254
It looks like Qt 5.6.1 has this fixed.

**Comment by jaakristioja** [comment]
Yep, that's the one. Closing.

**Comment by Geremia** [comment]
Perhaps I wasn't building against Qt5?

**Comment by jaakristioja** [comment]
@Geremia If you built from commit 95a393cc93edb58113538bd9d56361134d5929ab then by then we had already dropped support for Qt5.

**Comment by Geremia** [comment]
@jaakristioja okay, good to know. thanks

**Comment by Geremia** [comment]
It turns out my Qt5 webkit was packaged incorrectly on my distro; it was really a 3 year old version! I should've checked that first…
