### ISSUE TITLE
Crash when closing module display window with Qt 5.8

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#94]
Using Qt 5.8 open and then close any module display window will crash BibleTime.

**Comment by gholmlund** [comment]
Fixed

**Comment by Castir** [comment]
Not Fixed.  If I click to close one Bible or Personal commentary it has the same effect as File > Quit, Bibletime closes.  Ctl-Alt-W does the same as does Ctl-W.  Tried many times.  I am on a Lenovo G580 converted from Windows 8 to Mageia 6 Linux running on UEFI.  Several versions of Qt are in use from 4.3 thru 5.9.4 (auto installs).
